<?php

return array (
  'accountSettings' => 
  array (
    'companyName' => 'Company Name',
    'updateTitle' => 'Update Organization Settings',
    'companyEmail' => 'Company Email',
    'companyPhone' => 'Company Phone',
    'companyWebsite' => 'Company Website',
    'companyLogo' => 'Company Logo',
    'companyAddress' => 'Company Address',
    'defaultTimezone' => 'Default Timezone',
    'defaultCurrency' => 'Default Currency',
    'changeLanguage' => 'Change Language',
    'uploadLogo' => 'Upload your logo',
    'getLocation' => 'Set current location',
    'updateEnableDisable' => 'App Update',
    'updateEnableDisableTest' => 'Enable/Disable app update setting.',
  ),
  'roles' => 
  array (
    'addRole' => 'Manage Role',
  ),
  'permission' => 
  array (
    'projectNote' => 'User can view the basic details of projects assigned to him even without any permission.',
    'attendanceNote' => 'User can view his own attendance even without any permission.',
    'taskNote' => 'User can view the tasks assigned to him even without any permission.',
    'ticketNote' => 'User can view the tickets generated by him as default even without any permission.',
    'eventNote' => 'User can view the events to be attended by him as default even without any permission.',
    'selectAll' => 'Select All',
    'addRoleMember' => 'Manage Role Members',
    'addMembers' => 'Add Members',
    'roleName' => 'Role Name',
  ),
  'orders' => 
  array (
    'orderTitle' => 'Order Title',
    'orderDescription' => 'Order Description',
    'metaTitle' => 'Meta Title',
    'metaDescription' => 'Meta Description',
    'sectionVisibility' => 'Section Visibility',
    'profileImage' => 'Profile Image',
    'resume' => 'Resume',
    'coverLetter' => 'Cover Letter',
    'termsAndConditions' => 'Terms And Conditions',
  ),
  'front' => 
  array (
    'orderOpenings' => 'Order Openings',
    'visitMainWebsite' => 'Visit Main Website',
    'homeHeader' => 'Order Openings',
    'personalInformation' => 'Personal Information',
    'fullName' => 'Your Full Name',
    'email' => 'Your email address',
    'phone' => 'Your phone number',
    'photoFileType' => 'We accept PNG, JPG, and JPEG files',
    'photo' => 'Photo',
    'resume' => 'CV or Resume',
    'coverLetter' => 'Cover Letter',
    'submitOrder' => 'Submit Order',
    'additionalDetails' => 'Additional Details',
    'resumeFileType' => 'We accept JPEG, JPG, PNG, DOC, DOCX, RTF, XLS, XLSX and PDF files',
    'gender' => 'Gender',
    'dob' => 'Date Of Birth',
    'country' => 'Country',
    'male' => 'Male',
    'female' => 'Female',
    'others' => 'Others',
    'selectCountry' => 'Select Country',
    'selectState' => 'Select State',
    'selectCity' => 'Enter City Name',
    'yourAnswer' => 'Your Answer',
    'legalTerm' => 'Terms and Conditions',
    'agreeWithTerm' => 'I agree with the above Terms and Conditions',
  ),
  'orderApplication' => 
  array (
    'applicantName' => 'Applicant Name',
    'resume' => 'Resume',
    'appliedAt' => 'Applied at',
    'appliedFor' => 'Applied For',
    'status' => 'Status',
    'order' => 'Order',
    'location' => 'Location',
    'startDate' => 'Start Date',
    'sendDate' => 'End Date',
    'pending' => 'Pending',
    'approved' => 'Approved',
    'all' => 'All',
    'allStatus' => 'All Status',
    'allLocation' => 'All Location',
    'allOrders' => 'All Orders',
    'selectOrder' => 'Select Order',
    'addNote' => 'Add Note',
    'boardView' => 'Board View',
    'archiveApplication' => 'Archive Application',
    'deleteApplication' => 'Delete Application',
    'addSkills' => 'Add Skills',
    'skills' => 'Skills',
    'updateSkills' => 'Update skills',
    'enterName' => 'Search by Name',
    'unarchiveApplication' => 'Unarchive Application',
    'documents' => 'Documents',
    'viewDocuments' => 'View Documents',
    'document' => 
    array (
      'name' => 'Name',
      'file' => 'File',
      'fileNote' => 'We accept JPEG, JPG, PNG, GIF, TXT, DOC, DOCX, RTF, XLS, XLSX and PDF files'
    ),
    'newStatus' => 'New Status',
    'createStatus' => 'Create Status',
    'editStatus' => 'Edit Status',
    'statusName' => 'Name',
    'statusColor' => 'Color',
    'noChange' => 'No Change',
  ),
  'themeSettings' => 
  array (
    'themePrimaryColor' => 'Theme Primary Color',
    'adminPanelCustomCss' => 'Admin panel custom css',
    'frontSiteCustomCss' => 'Front site custom css',
  ),
  'dashboard' => 
  array (
    'totalCompanies' => 'Total Companies',
    'activeCompanies' => 'Active Companies',
    'inactiveCompanies' => 'Inactive Companies',
    'totalOrders' => 'Total Orders',
    'activeOrders' => 'Active Orders',
    'inactiveOrders' => 'Inactive Orders',
  ),
  'update' => 
  array (
    'systemDetails' => 'System Details',
    'updateTitle' => 'Update To New Version',
    'updateDatabase' => 'Update Database',
    'fileReplaceAlert' => 'To update the app to new version check documentation for the instructions.',
    'updateDatabaseButton' => 'Click to update database',
    'newUpdate' => 'New update available',
    'updateNow' => 'Update Now',
    'updateAlternate' => 'If the Update Now button does not work then follow the update instructions as mentioned in the documentation.',
  ),
  'company' => 
  array (
    'showFrontend' => 'Show company name in Frontend?',
  ),
  'sticky' => 
  array (
    'addNote' => 'Add Note',
    'lastUpdated' => 'Updated',
    'colors' => 'Colors',
  ),
  'module' => 
  array (
    'todos' => 
    array (
      'todoList' => 'ToDo List',
      'viewAll' => 'View All',
      'pendingTasks' => 'Pending Tasks',
      'completedTasks' => 'Completed Tasks',
      'noPendingTasks' => 'No pending tasks are available!',
      'noCompletedTasks' => 'No tasks are marked as completed.',
      'createTodoItem' => 'Create ToDo Item',
      'editTodoItem' => 'Edit ToDo Item',
      'form' => 
      array (
        'title' => 'Title',
        'status' => 'Status',
      ),
      'completed' => 'Completed',
      'pending' => 'Pending',
    ),
  ),
  'datatables' => 
  array (
    'emptyTable' => 'No data available in table',
    'info' => 'Total Records: _TOTAL_',
    'infoEmpty' => '',
    'infoFiltered' => '',
    'infoPostFix' => '',
    'lengthMenu' => 'Show _MENU_',
    'loadingRecords' => 'Loading...',
    'zeroRecords' => 'No matching records found',
    'paginate' => 
    array (
      'first' => 'First',
      'last' => 'Last',
      'next' => 'Next',
      'previous' => 'Previous',
    ),
    'aria' => 
    array (
      'sortAscending' => ': activate to sort column ascending',
      'sortDescending' => ': activate to sort column descending',
    ),
    'processing' => "<i class='ti-loop'></i>  Loading...",
    'search' => 'Search:',
    'infoThousands' => ',',
  ),
  'languageSettings' => 
  array (
    'defaultLanguageCannotBeModified' => 'Default language cannot be updated or deleted.',
    'statusDisabledNote' => 'Cannot change status of Active Language',
  )
);
