<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>iRequest Privacy Policy</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
            }

            header {
                text-align: center;
                padding: 10px;
                background-color: #f0f0f0;
            }

            img {
                max-width: 100%;
                height: auto;
            }
        </style>
    </head>

    <body>
        <header>
            <a class="d-flex" href="https://imedicalhs.com" title="imedicalhs">
                <img class="img-logo" src="{{ asset('assets/login/images/logo.png') }}" alt="logo">
            </a>
        </header>

        <h1>iRequest Terms & Conditions - iMedical healthcare solutions</h1>

        <h2>1. Acceptance of Terms</h2>
        <h3>1.1 By using iRequest:</h3>
        <p>By accessing or using the iRequest application, you agree to comply with and be bound by these Terms and Conditions.</p>

        <!-- Add other sections as needed -->

        <h2>2. User Responsibilities</h2>
        <h3>2.1 User Conduct:</h3>
        <p>Users are responsible for maintaining the confidentiality of their account information and ensuring the accuracy of the information provided.</p>

        <!-- Add other sections as needed -->

        <h3>2.2 Prohibited Activities:</h3>
        <p>Users must not engage in activities that violate laws, regulations, or the rights of other users.</p>

        <!-- Add other sections as needed -->

        <h2>3. Orders and Billing</h2>
        <h3>3.1 Order Creation:</h3>
        <p>Users are responsible for providing accurate and complete information when creating medical equipment orders.</p>

        <!-- Add other sections as needed -->

        <h3>3.2 Billing Reports:</h3>
        <p>Billing reports generated by the system are based on the information provided by users. Users are responsible for reviewing and verifying the accuracy of billing information.</p>

        <!-- Add other sections as needed -->

        <h2>4. SMS Terms & Conditions</h2>
        <p>iMedical Healthcare Solutions, also known as 'iMedical' and iRequest, offers the option to our customers to engage in conversations with our service to provide fast solutions and monitor the orders delivery status and tracking; Message frequency varies; Message and data rates may apply; Text HELP to (+1) 8888813665 for help; Reply STOP to cancel; Carriers are not liable for any delays or undelivered messages.</p>


        <h2>5. Limitation of Liability</h2>
        <p>iMedical Healthcare Solutions is not liable for any direct, indirect, incidental, or consequential damages arising from the use of iRequest.</p>

        <!-- Add other sections as needed -->

        <h2>6. Dispute Resolution</h2>
        <p>Any disputes arising from the use of iRequest will be resolved through arbitration in accordance with applicable laws.</p>
    </body>

</html>
